name: Deploy to Heroku

on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout 
        uses: actions/checkout@main
      
      - name: Deploy to Heroku
        uses: akhileshns/heroku-deploy@master
        with:
          stack: "container"
          region: "us"
          usedocker: true
          heroku_email: ${{ secrets.HEROKU_EMAIL }}
          heroku_api_key: ${{ secrets.HEROKU_API_KEY }}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME }}
          docker_heroku_process_type: web
          
        env:
          HD_CONFIG_FILE_URL: ${{ secrets.CONFIG_FILE_URL }}